version: '3.7'

services: 
  tf: 
    environment: 
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # - TF_LOG=DEBUG

    image: "hashicorp/terraform:0.14.7"
    volumes: 
      - ".:/IAC"
    working_dir: /IAC